#ifndef BEHAVIOUR_H
#define BEHAVIOUR_H

#define NOTSET -1
#define GOFORWARD 0
#define TURNTOWARDSENSOR 1
#define CHECKIFFIRE 2
#define BOUNCEAWAY 3
#define EXTINGUISHFIRE 4

#define FASTPACE 600
#define SLOWPACE 300

#define BOUNCEANGLEFRONTRIGHT 165
#define BOUNCEANGLESIDERIGHT 130
#define BOUNCEANGLESIDELEFT -130
#define BOUNCEANGLEFRONTLEFT -165

#define FRONTRIGHT 0
#define FRONTLEFT 7
#define SIDERIGHT 1
#define SIDELEFT 6

void process_state_machine_start(void);

#endif